### ISSUE TITLE
Parabenização.

### ISSUE THREAD

**Issue by gabrafo** [ribeirogabe/Jogo-da-memoria-Pokemon#1]
Sendo sincero, estou começando agora no desenvolvimento com JavaScript e achei o seu projeto extremamente bonito e simples! Acho isso uma coisa bastante interessante e também acho importante elogiar e deixar isso claro mesmo que de maneira breve. Obrigado por compartilhar esse projeto na plataforma!

**Comment by ribeirogabe** [comment]
Eu fico muito feliz e agradeço demais pelo elogio! Fico muito feliz que tenha gostado, estou estudando JavaScript faz um tempinho e estou gostando demais! Espero que tenha sucesso nessa caminhada! Muito obrigado novamente!

**Comment by ribeirogabe** [comment]
> Sendo sincero, estou começando agora no desenvolvimento com JavaScript e achei o seu projeto extremamente bonito e simples! Acho isso uma coisa bastante interessante e também acho importante elogiar e deixar isso claro mesmo que de maneira breve. Obrigado por compartilhar esse projeto na plataforma!

Eu fico muito feliz e agradeço demais pelo elogio! Fico muito feliz que tenha gostado, estou estudando JavaScript faz um tempinho e estou gostando demais! Espero que tenha sucesso nessa caminhada! Muito obrigado novamente!
